import React from 'react';
import { Routes, Route } from 'react-router-dom';
import '../assets/css/tailwind.css';
import Home from './components/Home';
import About from './components/About';
function NewTab() {
    return (React.createElement("div", { className: "App bg-slate-100 min-h-screen" },
        React.createElement("aside", { className: "App-sidebar hidden md:block fixed top-0 left-0 w-64 min-h-screen bg-white shadow" },
            React.createElement("div", { className: "App-sidebar-logo flex justify-center px-2 py-3" },
                React.createElement("h1", { className: "text-2xl" },
                    React.createElement("img", { src: "/", className: "logo inline mr-2 -mt-1", alt: "WebDev HQ Logo" }),
                    React.createElement("span", { className: "web" }, "Web"),
                    React.createElement("span", { className: "dev-hq font-medium" }, "Dev HQ"))),
            React.createElement("section", { className: "sidebar-section mt-10 mb-6" },
                React.createElement("h2", { className: "text-1xl font-medium mx-5 my-3" }, "SVG Todos"),
                React.createElement("ul", { className: "sidebar-nav" },
                    React.createElement("li", null,
                        React.createElement("a", { href: "/", className: "block px-4 py-2 bg-sky-100 border-r-2 border-r-sky-500" }, "SVG All Todos"))))),
        React.createElement("header", { className: "App-header flex fixed top-0 md:ml-64 w-screen p-2 bg-white shadow" },
            React.createElement("nav", { className: "flex justify-between w-max" },
                React.createElement("span", { className: "p-0" },
                    React.createElement("a", { href: "/", className: "md:hidden" },
                        React.createElement("img", { src: "#", className: "logo inline mx-2 -mt-1", alt: "WebDev HQ Logo" })),
                    React.createElement("button", { className: "bg-slate-200 hidden md:inline hover:bg-slate-300 ml-3 mr-1 rounded p-2 pt-1", id: "btn-sidebar-toggle" }, "SVG"),
                    React.createElement("input", { type: "search", name: "search", className: "search-input-mobile md:hidden p-2 border rounded-md ml-3 mt-1", placeholder: "Search" }),
                    React.createElement("input", { type: "search", name: "search", className: "search-input-desktop hidden md:inline p-2 border rounded-md ml-3 mt-1", placeholder: "Search / CTRL + K" })),
                React.createElement("button", { className: "fixed right-5 md:hidden bg-slate-200 rounded p-2" }, "SVG"),
                React.createElement("ul", { className: "hidden fixed right-5 md:inline-flex md:mt-1" },
                    React.createElement("li", null,
                        React.createElement("button", { className: "bg-slate-200 mx-2 inline-flex p-3 rounded" }, "SVG")),
                    React.createElement("li", null,
                        React.createElement("button", { className: "bg-slate-200 mx-2 inline-flex p-3 rounded" }, "SVG")),
                    React.createElement("li", null,
                        React.createElement("button", { className: "bg-slate-200 mx-2 inline-flex p-3 rounded" }, "SVG")),
                    React.createElement("li", null,
                        React.createElement("button", { className: "bg-slate-200 mx-2 inline-flex p-3 rounded" }, "SVG")),
                    React.createElement("li", null,
                        React.createElement("button", { className: "bg-slate-200 mx-2 inline-flex p-3 rounded" }, "SVG")),
                    React.createElement("li", null,
                        React.createElement("button", { className: "bg-slate-200 mx-2 inline-flex p-3 rounded" }, "SVG"))))),
        React.createElement("div", { className: "pt-16 pl-4 pr-4 md:pl-72 md:pt-24 md:w-full min-h-screen" },
            React.createElement("div", { className: "breadcrumb-navigation mb-6" },
                React.createElement("ul", { className: "flex" },
                    React.createElement("li", null,
                        React.createElement("a", { href: "/" }, "WebDev HQ")),
                    React.createElement("li", null,
                        React.createElement("a", { href: "#" }, "Todos")))),
            React.createElement("main", { className: "md:w-full" },
                React.createElement(Routes, null,
                    React.createElement(Route, { path: "/", element: React.createElement(Home, null) }),
                    React.createElement(Route, { path: "/about", element: React.createElement(About, null) }))))));
}
export default NewTab;
